- assets/js/admin.js
- includes/views/setting.php
- readme.txt
- thrivedesk.php
- changelog and plugin version
- updated post sync integration tab border style
> WordPress Post Sync integration

- src/Api.php
- src/Plugins/WooCommerce.php
- thrivedesk.php
WooCommerce order status check functionality for ThriveDesk Assistant order status
> [ADD] - WooCommerce order status check functionality

- Hooks/FluentCrmHooks.php
- database/DBMigrator.php
- database/TDConversation.php
- src/Abstracts/Plugin.php
- src/Admin.php
- src/Api.php
- src/Plugins/FluentCRM.php
- thrivedesk.php
Now we have a trash conversation feature in ThriveDesk. So ThriveDesk WordPress plugin is now updated with ThriveDesk trash conversation dependency.
```diff
! TODO:
-  Truncate conversation subject
-  Changelog
```
> [UPDATE] - Fluent CRM dependency

- readme.txt
- src/Abstracts/Plugin.php
- src/Plugins/EDD.php
- thrivedesk.php
EDD sites URL was broken. Fixed those broken links issue.
Also added EDD customer and WordPress user info on widget.
> [DEV-720] - added customer info for EDD

- readme.txt
- thrivedesk.php
WordPress has just been released with version 5.9. Added our plugin support up to version 5.9 as dependency
> chore(wordpress): updated with WordPress version 5.9

- src/Plugins/WooCommerce.php
"get_edit_order_url" method was added to get the order URL. This URL will pass as API data for the frontend app.
Dependency : https://github.com/thrivedesk/app-frontend/pull/454
> refactor: order edit url added.

- src/Abstracts/Plugin.php
- src/Api.php
- src/Plugins/WooCommerce.php
**Now you can stop shipping queries from the frontend app.** 
**Before:**
**After:**
> refactor: optimized shipping details 

- src/Plugins/WooCommerce.php
Now we are able to identify a contact that is a normal customer or a guest customer. 
Related pull request : https://github.com/thrivedesk/app-frontend/pull/468
> feat: is guest customer identifier added

- src/Abstracts/Plugin.php
- src/Admin.php
- src/Api.php
- src/Api/ApiResponse.php
- src/Plugins/Autonami.php
- src/Plugins/EDD.php
- src/Plugins/FluentCRM.php
- src/Plugins/SmartPay.php
- src/Plugins/WPPostSync.php
- src/Plugins/WooCommerce.php
- src/RestRoute.php
This data will help us to show extra info where the **no license found**  message was displaced.
Related PR: https://github.com/thrivedesk/app-frontend/pull/470
> refactor: products data

- readme.txt
- thrivedesk.php
> Readme update for dev

- .github/workflows/push-asset-readme-update.yml
- readme.txt
- thrivedesk.php
> Dev to Master

- includes/views/shortcode/conversation-details.php
- package.json
- readme.txt
- thrivedesk.php
1. Fix: Conversation detail shows the status update information
2. Update previous version release notes
3. update new version information
> Fix: Conversation detail shows the status update information

- includes/views/shortcode/conversations.php
- package.json
- readme.txt
- resources/css/admin.css
- resources/css/thrivedesk.css
- src/Conversations/Conversation.php
- thrivedesk.php
= 1.0.7 =
- Added footer credit on conversations page
- Fixed WP footer overlapping issue on portal settings
- Fixed UTF-8 email parsing issue
> feat: TD footer credit, fix: wp footer overlapping issue, email parsing issue

- includes/views/shortcode/conversation-details.php
- package.json
- readme.txt
- resources/languages/thrivedesk.pot
- thrivedesk.php
1. Added translation file (en)
2. support for rtl
> feat: language support

- package.json
- readme.txt
- src/Services/PortalService.php
- thrivedesk.php
= 1.0.10 =
- Fixed portal feature availability issue
> fix: portal feature was not available

- database/Scripts/MigrationScript.php
run migration script on plugin update
> feat: run migration script on plugin update

- package.json
- readme.txt
- src/Services/PortalService.php
- thrivedesk.php
= 1.0.15 =
- Update: ThriveDesk plan list for Portal feature
> fix: added agency plan that was previously missed

- readme.txt
This PR fixes the brand name and some other typo issue.
> fix: typo and brand name

- includes/helper.php
- includes/views/pages/settings.php
- resources/js/admin.js
- src/Conversations/Conversation.php
- thrivedesk.php
Token validation issue fixed and warning messages updated.
> fix: portal token verification issues

- includes/views/pages/settings.php
- resources/js/admin.js
> fix: token verification warnings

- includes/views/pages/settings.php
Portal warnings with Blank API key, issues handled.
> fix: blank api key warnings 

- readme.txt
- src/Plugins/WooCommerce.php
- thrivedesk.php
- This enhancement includes the ability to track customer orders, providing better visibility into the order fulfillment process.
- Implemented support for custom Order IDs in the TD-WooCommerce widget, allowing users to use personalized identifiers for their orders.
- Added tracking info to customer orders to enhance order management.
- Custom Order ID support in the TD-WooCommerce widget enables users to set custom identifiers for orders.
https://github.com/thrivedesk/app-frontend/pull/874
> feat : Added tracking info to customer orders and custom Order Id support with TD-WooCommerce widget.

- src/Plugins/WooCommerce.php
Woocommerce custom order plugin support added.
> feat: added wc custom order plugin support

- package-lock.json
- package.json
- readme.txt
- src/Plugins/WooCommerce.php
- thrivedesk.php
Reverts thrivedesk/wp-thrivedesk#80
> Revert "feat: added wc custom order plugin support"

- composer.json
- package.json
- readme.txt
- thrivedesk.php
The plugin is relocated to the main menu with legacy.
> feat: plugin relocated with legacy

- includes/views/partials/settings.php
- includes/views/shortcode/modal.php
- readme.txt
- resources/js/conversation.js
- src/Admin.php
- src/KnowledgeBase/KnowledgeBase.php
- thrivedesk.php
- Update: Modal UI
- Fix : Search infinite loading
- Fix : knowledge warnings
> Feat/wp thrivedest 2.0.1

- readme.txt
- src/Plugins/WooCommerce.php
- src/Services/PortalService.php
- thrivedesk.php
Payment & Shipping Methods added
> feat: Payment & Shipping Methods added

- includes/views/setting.php
- resources/js/admin.js
- src/Admin.php
- src/Conversations/Conversation.php
https://github.com/thrivedesk/app-frontend/pull/1058
> feat: Organization info added to the dashboard

- includes/views/setting.php
- readme.txt
- resources/js/admin.js
- src/Admin.php
- src/Conversations/Conversation.php
- src/Plugins/Autonami.php
- thrivedesk.php
Reverts thrivedesk/wp-thrivedesk#93
> Revert "Users can control the assistant's visibility based on their routes."

- includes/views/shortcode/conversation-details.php
- src/Conversations/Conversation.php
> fix: note visibility issue
